FROM python:3.9-slim
WORKDIR /app
COPY consumer/metrics_consumer.py /app/consumer.py
RUN pip install --no-cache-dir kafka-python prometheus_client
RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*
CMD ["python", "consumer.py"]
EXPOSE 8000
